version: '3'
services:
  gotenberg1:
    image: thecodingmachine/gotenberg:7
    ports:
      - "3001:3000"

  gotenberg2:
    image: thecodingmachine/gotenberg:7
    ports:
      - "3002:3000"

  gotenberg3:
    image: thecodingmachine/gotenberg:7
    ports:
      - "3003:3000"

  gotenberg4:
    image: thecodingmachine/gotenberg:7
    ports:
      - "3004:3000"

  gotenberg5:
    image: thecodingmachine/gotenberg:7
    ports:
      - "3005:3000"

  gotenberg6:
    image: thecodingmachine/gotenberg:7
    ports:
      - "3006:3000"

  nginx:
    image: nginx:latest
    ports:
      - "3000:3000"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - gotenberg1
      - gotenberg2
      - gotenberg3
      - gotenberg4
      - gotenberg5
      - gotenberg6
